[package]
name = "heartprotocol"
version = "1.0.0"
authors = ["Sidharth P"]

[addresses]
heartprotocol = "0x2c9932c0e6a2567d80c78c313fc95b94f9f289febb1559d39991d3ca35f39df4"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet" }
