[package]
name = "heartprotocol"
version = "1.0.0"
authors = ["Sidharth P"]

[addresses]
heartprotocol = "0x95dafdddcc859cea363db8cbc0907adf3470599ea143c527dee232586cf97c45"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet" }

